<<<<<<< HEAD
---
- name: get VM info
  hosts: localhost
  connection: local
  tasks:
    - name: Get VM info
      azure_rm_resource_facts:
        resource_group: myRG
        resource_name: myVM
        api_version: '2018-06-01'
        resource_type: virtualmachines
        provider: compute
        subresource: 
          - type: instanceview
      register: output
    - debug:
        var: output




PLAY [get VM info] ***********************************************************************************

TASK [Gathering Facts] *******************************************************************************
ok: [localhost]

TASK [Get VM info] ***********************************************************************************
 [WARNING]: Azure API profile latest does not define an entry for GenericRestClient

ok: [localhost]

TASK [debug] *****************************************************************************************
ok: [localhost] => {
    "output": {
        "changed": false, 
        "failed": false, 
        "response": [
            {
                "computerName": "myVM", 
                "disks": [
                    {
                        "name": "myVM", 
                        "statuses": [
                            {
                                "code": "ProvisioningState/succeeded", 
                                "displayStatus": "Provisioning succeeded", 
                                "level": "Info", 
                                "time": "2018-11-19T06:44:18.0842987+00:00"
                            }
                        ]
                    }
                ], 
                "osName": "ubuntu", 
                "osVersion": "16.04", 
                "statuses": [
                    {
                        "code": "ProvisioningState/succeeded", 
                        "displayStatus": "Provisioning succeeded", 
                        "level": "Info", 
                        "time": "2018-11-19T06:45:53.0848719+00:00"
                    }, 
                    {
                        "code": "PowerState/running", 
                        "displayStatus": "VM running", 
                        "level": "Info"
                    }
                ], 
                "vmAgent": {
                    "extensionHandlers": [], 
                    "statuses": [
                        {
                            "code": "ProvisioningState/succeeded", 
                            "displayStatus": "Ready", 
                            "level": "Info", 
                            "message": "Guest Agent is running", 
                            "time": "2018-11-19T07:09:50+00:00"
                        }
                    ], 
                    "vmAgentVersion": "2.2.32.2"
                }
            }
        ], 
        "url": "/subscriptions/2085065b-00f8-4cba-9675-ba15f4d4ab66/resourceGroups/myRG/providers/Microsoft.compute/virtualmachines/myVM/instanceview", 
        "warnings": [
            "Azure API profile latest does not define an entry for GenericRestClient"
=======
ansible-playbook  1.yml 
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note
that the implicit localhost does not match 'all'


PLAY [for issue 48725 test] ****************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [get VM info when VM is not exist] ****************************************
 [WARNING]: Error getting virtual machine myVM01 - Azure Error:
ResourceNotFound Message: The Resource
'Microsoft.Compute/virtualMachines/myVM01' under resource group 'myRG' was not
found.

ok: [localhost]

TASK [dump log] ****************************************************************
ok: [localhost] => {
    "output1": {
        "changed": false, 
        "failed": false, 
        "vms": [], 
        "warnings": [
            "Error getting virtual machine myVM01 - Azure Error: ResourceNotFound\nMessage: The Resource 'Microsoft.Compute/virtualMachines/myVM01' under resource group 'myRG' was not found."
        ]
    }
}

TASK [get VM info when VM is stop] *********************************************
ok: [localhost]

TASK [dump log] ****************************************************************
ok: [localhost] => {
    "output2": {
        "changed": false, 
        "failed": false, 
        "vms": [
            {
                "admin_username": "azureuser", 
                "data_disks": [], 
                "id": "/subscriptions/2085065b-00f8-4cba-9675-ba15f4d4ab66/resourceGroups/myRG/providers/Microsoft.Compute/virtualMachines/myVM", 
                "image": {
                    "offer": "UbuntuServer", 
                    "publisher": "Canonical", 
                    "sku": "16.04-LTS", 
                    "version": "latest"
                }, 
                "location": "eastus", 
                "name": "myVM", 
                "network_interface_names": [
                    "myvm2"
                ], 
                "os_disk_caching": "ReadWrite", 
                "os_type": "Linux", 
                "resource_group": "myRG", 
                "state": "present", 
                "tags": {}, 
                "vm_size": "Standard_D2s_v3"
            }
>>>>>>> 517d4c7d077285214dc369729fb1f3b9987b46f4
        ]
    }
}

<<<<<<< HEAD
=======
PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0   

fred@fred-Virtual-Machine:~/task$ ansible --version
ansible 2.7.1
  config file = None
  configured module search path = [u'/home/fred/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
>>>>>>> 517d4c7d077285214dc369729fb1f3b9987b46f4

