---
- hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  tasks:
    - name: query
      azure_rm_resourcegroup_info:
      register: output

    - debug:
        var: output

    - name: delete named startwith ansibletest
      azure_rm_resourcegroup:
        name: "{{ item }}"
        state: absent
        force: yes
      with_items: "{{ output | json_query('resourcegroups[*].name') | select('match', 'ansibletest') | list }}"
      async: 10000
      poll: 0
      register: jobs

      #- name: Wait for complete
      # async_status: jid={{ item.ansible_job_id }}
      # register: job
      # until: job.finished
      #retries: 300
      #with_items: "{{ jobs.results }}"

    - name: delete named start with sampletest
      azure_rm_resourcegroup:
        name: "{{ item }}"
        state: absent
        force: yes
      with_items: "{{ output | json_query('resourcegroups[*].name') | select('match', 'sampletest') | list }}"
      async: 10000
      poll: 0
      register: jobs

      #- name: Wait for complete
      #async_status: jid={{ item.ansible_job_id }}
      #register: job
      #until: job.finished
      #retries: 300
      #with_items: "{{ jobs.results }}"
