# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
# Just for test

trigger: 
  - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: A
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
        displayName: 'Use Python $(python.version)'

      - script: tests/utils/weekly/delete_rg.sh
        displayName: 'Install ansible and excute ansible'
        env:
          AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
          AZURE_SECRET: $(AZURE_SECRET)
          AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
          AZURE_TENANT: $(AZURE_TENANT)

  - job: B
    steps:
      - bash: |
         echo 'TEST PASS'
         echo 'TEST PASS'
